pgdata:
  image: postgres:9.3
  volumes:
    - /var/lib/postgresql/data
  command: echo 'true linha 5'

postgres:
  image: postgres:9.3
  volumes_from:
    - pgdata
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password

pentahodata:
  image: java:7
  volumes:
    - /pentaho-data
  command: echo 'true linha 21'

pentaho:
  image: leandrocp/pentaho-server
  volumes_from:
    - pentahodata
  links:
    - postgres:postgres
  ports:
    - "8080:8080"
  environment:
    DB_USER: postgres
    DB_PASS: password

omnidb:
  image: taivokasper/omnidb
  volumes:
    - config-omnidb:/etc/omnidb 
  links:
    - postgres:postgres
  ports:
    - "8090:8080"
    - "25482:25482"

jenkins:
  image: jenkins/jenkins:lts
  volumes_from:
    - pgdata 
  links:
    - postgres:postgres
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8081:8080"
  volumes:
    - /var/jenkins_home